#!/bin/bash
# Exercises the pyke command line end to end: generation, safety guards, --clean, --init, --fmt, build/test.
# usage: tests/run_cli_tests.sh <path-to-pyke-binary>
set -u
PYKE="$(realpath "${1:?usage: run_cli_tests.sh <pyke-binary>}")"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
passed=0
failed=0

check() { # check <description> <command...>: passes when the command succeeds
    local desc="$1"; shift
    if "$@" >/dev/null 2>&1; then passed=$((passed + 1)); echo "  PASS: $desc"
    else failed=$((failed + 1)); echo "  FAIL: $desc"; fi
}
fails() { ! "$@"; }
contains() { grep -q -- "$2" "$1"; }

newproj() { # newproj <name>: a one-target project in $WORK/<name>
    mkdir -p "$WORK/$1/app"
    cat > "$WORK/$1/app.pyke" <<'P'
project("T", lang="c++17")

@Executable("app")
target app():
    def configure(self):
        self.sources = ["main.cpp"]
P
    echo 'int main() { return 0; }' > "$WORK/$1/app/main.cpp"
}

echo "generation"
newproj gen
cd "$WORK/gen"
"$PYKE" app.pyke . > out.log 2>&1
check "writes the root and target files" test -f CMakeLists.txt -a -f app/CMakeLists.txt
check "records a manifest" test -f .pyke/generated
check "second run writes nothing" contains <("$PYKE" app.pyke . 2>&1) "0 written"

echo "overwrite guard"
newproj guard
cd "$WORK/guard"
echo "# my own cmake" > CMakeLists.txt
check "refuses to overwrite a hand-written file" fails "$PYKE" app.pyke .
check "hand-written file is untouched" contains CMakeLists.txt "my own cmake"
check "--force overwrites it" "$PYKE" --force app.pyke .
check "file is now generated" contains CMakeLists.txt "Generated by pyke"

echo "--clean"
newproj clean
cd "$WORK/clean"
"$PYKE" app.pyke . >/dev/null 2>&1
sed -i 's/@Executable("app")/@Executable("app2")/; s/main.cpp/main2.cpp/' app.pyke
"$PYKE" app.pyke . >/dev/null 2>&1
check "stale file is kept without --clean" test -f app/CMakeLists.txt
"$PYKE" --clean app.pyke . >/dev/null 2>&1
check "--clean removes the stale file" test ! -f app/CMakeLists.txt
check "--clean keeps the current files" test -f app2/CMakeLists.txt

echo "validation and errors"
newproj bad
cd "$WORK/bad"
printf 'project("T")\n@Executable("a")\ntarget a(PRIVATE nothere):\n    def configure(self):\n        self.sources = ["m.cpp"]\n' > bad.pyke
check "--validate fails on an unknown dependency" fails "$PYKE" --validate bad.pyke
check "nothing is generated on error" fails test -f CMakeLists.txt
check "--validate passes on a good file" "$PYKE" --validate app.pyke
check "a missing input file fails" fails "$PYKE" nope.pyke .

echo "output containment"
newproj escape
cd "$WORK/escape"
printf 'project("T")\n@Executable("../outside")\ntarget a():\n    def configure(self):\n        self.sources = ["m.cpp"]\n' > esc.pyke
check "a target path outside the project is rejected" fails "$PYKE" esc.pyke .
check "nothing was written outside" test ! -d "$WORK/outside"

echo "stubs and source warnings"
newproj stubs
cd "$WORK/stubs"
printf 'project("T")\n@Executable("app")\ntarget app():\n    def configure(self):\n        self.sources = ["main.cpp", "util.cpp"]\n' > app.pyke
rm app/main.cpp
"$PYKE" app.pyke . >/dev/null 2>&1
check "missing sources get stubs" test -f app/main.cpp -a -f app/util.cpp
check "a main stub has main()" contains app/main.cpp "int main"
touch app/forgotten.cpp
check "unlisted source files are reported" contains <("$PYKE" app.pyke . 2>&1) "forgotten.cpp"
printf 'project("T")\n@StaticLibrary("lib")\ntarget lib():\n    def configure(self):\n        self.sources = ["*.cpp"]\n' > glob.pyke
mkdir -p lib
check "an empty glob is reported" contains <("$PYKE" glob.pyke . 2>&1) 'matches no files'

echo "C++ modules"
newproj mods
cd "$WORK/mods"
printf 'project("T", lang="c++20")\n@StaticLibrary("m")\ntarget m():\n    def configure(self):\n        self.exports.modules = ["my-mod.cppm"]\n' > mods.pyke
"$PYKE" mods.pyke . >/dev/null 2>&1
check "module files get an export module stub" contains m/my-mod.cppm "export module my_mod;"
check "modules raise the minimum CMake version" contains CMakeLists.txt "VERSION 3.28"
sed -i 's/c++20/c++17/' mods.pyke
check "modules on c++17 are rejected" fails "$PYKE" --validate mods.pyke

echo "--init"
mkdir -p "$WORK/init/src" "$WORK/init/include"
echo 'int main() { return 0; }' > "$WORK/init/src/main.cpp"
cd "$WORK/init"
check "--init creates a .pyke file" "$PYKE" --init .
check "--init output validates" "$PYKE" --validate "$(ls ./*.pyke | head -1)"
check "--init refuses to overwrite" fails "$PYKE" --init .

echo "--fmt"
newproj fmt
cd "$WORK/fmt"
printf 'project( "T" ,lang="c++17")\n\n\n@Executable("app")\ntarget app():\n\tdef configure(self):\n\t\tself.sources=["main.cpp"]  \n' > messy.pyke
check "--fmt --check fails on an unformatted file" fails "$PYKE" --fmt --check messy.pyke
check "--check does not modify the file" contains messy.pyke "self.sources=\["
check "--fmt reformats" "$PYKE" --fmt messy.pyke
check "--fmt --check passes afterwards" "$PYKE" --fmt --check messy.pyke
check "formatted output keeps its meaning" "$PYKE" --validate messy.pyke

echo "build and test"
if command -v cmake >/dev/null 2>&1; then
    newproj build
    cd "$WORK/build"
    sed -i 's/@Executable("app")/@Executable("app", test=True)/' app.pyke
    check "pyke test builds and runs ctest" "$PYKE" test
    check "build lands in build/" test -f build/CMakeCache.txt
    check "pyke build --debug works" "$PYKE" build --debug
    check "pyke build rejects unknown flags" fails "$PYKE" build --bogus
else
    echo "  SKIP: cmake not found"
fi

echo
echo "CLI tests: $passed passed, $failed failed"
[ "$failed" -eq 0 ]
